### ISSUE TITLE
Moonchain

### ISSUE THREAD

**Issue by SanghamitraBhowmick1993** [MXCzkEVM/MEP-1759-DApp-store#36]
https://www.notion.so/wannsee-roadmap/Moonchain-6347382ca176454bba225169b1eec022

**Comment by sheenhx** [comment]
geneva-nft.moonchain.com
geneva-swap-info.moonchain.com
geneva-mns.moonchain.com
geneva-depinscriptions.moonchain.com
airdrop.moonchain.com

@SanghamitraBhowmick1993 please double check and if ok then let Hairy to deploy to mainnet

**Comment by sheenhx** [comment]
Another thing to test is the wallet connect sequence
Should be 
1. Axs wallet
2. metamask
3. okx Web3 wallet
on all Dapps, please also QA this

**Comment by SanghamitraBhowmick1993** [comment]
I cannot proceed from the screen below when attempting to MINT Hexagon @hairyf 

![Image](https://github.com/MXCzkEVM/MEP-1759-DApp-store/assets/93600163/c1ae7a99-dcec-4cae-a84b-7815204a8263)

**Comment by SanghamitraBhowmick1993** [comment]
When connecting my account, I still see Metamask listed as the primary option instead of AXS for MNS - Geneva

![Image](https://github.com/MXCzkEVM/MEP-1759-DApp-store/assets/93600163/bbfb1a67-ebb1-47b2-b7f3-6211fe3fe165)

**Comment by sheenhx** [comment]
@SanghamitraBhowmick1993 please test bridge and swap-info geneva

**Comment by SanghamitraBhowmick1993** [comment]
Update for tests on geneva:

Good to go:
https://geneva-xsd.moonchain.com/markets/ -yes
https://geneva-erc20.moonchain.com/ -yes
[geneva-nft.moonchain.com](http://geneva-nft.moonchain.com/) - yes
[geneva-mns.moonchain.com](http://geneva-mns.moonchain.com/) - yes
[airdrop.moonchain.com](http://airdrop.moonchain.com/) - yes
https://geneva-swap.moonchain.com/  - yes
https://geneva-explorer.moonchain.com/  - yes

Bug fixes in progress:
https://depinscriptions.moonchain.com/  - no
https://geneva-swap-info.moonchain.com/pairs - no

cc: @hairyf @sheenhx
